### PR TITLE
Add a python 3.11 container (for use with SRAM)

### PR DESCRIPTION
**Pull request by baszoetekouw**

### CODE REVIEW

**Review by quartje — COMMENTED** [review]
In other projects we tend to stick to the official Apache containers. It adds stuff like logging to stdout in stead of a logfile, amongst other things. The philosophy of OpenConext-BaseContainers is to stay as close as possible to the official containers. Or are there any reasons not to do so?

**Comment by baszoetekouw** [comment]
@mrvanes is there any reason to not use the standard Apache containers?

**Comment by mrvanes** [comment]
Yes, they do not support a2enmod

**Comment by baszoetekouw** [comment]
Hmm, indeed the offical "solution" seems rather clunky: https://stackoverflow.com/questions/60591893/how-to-enable-mod-rewrite-module-for-docker-official-httpd-image

@quartje what do you think?  How do you handle this for the OpenConext images?  Surely those also need to enable Apache mods?

**Comment by quartje** [comment]
@baszoetekouw We're preparing a container where all modules we need are enabled (like mod_rewrite and mod_proxy) so you can use that as a base image. Coming to a container registry near you this week :)

**Comment by baszoetekouw** [comment]
@quartje I've removed the Apache container from this PR; I'll also ask Martin to change the python container to a container based on the upstream python containers (https://hub.docker.com/_/python)

When do you expect the plain Apache container to be merged?

**Comment by baszoetekouw** [comment]
Is obsolete now, we use the upstream python image directly.

**Pull request closed without merging**
