### PR TITLE
Adding the possibility to run as an arbitrary user

### PR DESCRIPTION
**Pull request by danakim**

### CODE REVIEW

**Comment by quartje** [comment]
It's not working as expected yet. I am adding the following as environment variable:
APACHE_RUN_USER: #1021
And the error is:
chown: invalid spec: '1021':

**Comment by danakim** [comment]
@quartje - there was an error in my logic when chowing. Fixed in the last commit. Can you please pull, rebuild and try again?

**Comment by quartje** [comment]
It works. However, restarting a container fails:
```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
[Wed Nov 01 09:15:39.728399 2023] [mpm_event:notice] [pid 21:tid 140245984449664] AH00489: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Wed Nov 01 09:15:39.728450 2023] [core:notice] [pid 21:tid 140245984449664] AH00094: Command line: 'apache2 -D FOREGROUND'
useradd: user 'openconext' already exists
```

**Review by quartje — APPROVED** [review]
It works! 
Lets merge :)

**Pull request merged**
